I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 26, in script
    n "You are home."
Exception: The say screen (or show_function) must return a Text object.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 26, in script
    n "You are home."
  File "D:\Ren'Py\renpy-8.3.7-sdk\renpy\ast.py", line 2586, in execute
    Say.execute(self)
  File "D:\Ren'Py\renpy-8.3.7-sdk\renpy\ast.py", line 623, in execute
    renpy.exports.say(who, what, *args, **kwargs)
  File "D:\Ren'Py\renpy-8.3.7-sdk\renpy\exports\sayexports.py", line 132, in say
    who(what, *args, **kwargs)
  File "D:\Ren'Py\renpy-8.3.7-sdk\renpy\character.py", line 1471, in __call__
    self.do_display(who, what, cb_args=self.cb_args, dtt=dtt, **display_args)
  File "D:\Ren'Py\renpy-8.3.7-sdk\renpy\character.py", line 1117, in do_display
    display_say(who,
  File "D:\Ren'Py\renpy-8.3.7-sdk\renpy\character.py", line 764, in display_say
    raise Exception("The say screen (or show_function) must return a Text object.")
Exception: The say screen (or show_function) must return a Text object.

Windows-10-10.0.19045 AMD64
Ren'Py 8.3.7.25031702
Contamination Protocol 0.2
Sun Jul  6 18:09:23 2025
