I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 383, in script
    call screen buttons()
ScriptError: could not find label 'candy_route'.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "C:\Users\patty\Documents\renpy-8.3.7-sdk\renpy\bootstrap.py", line 359, in bootstrap
    renpy.main.main()
  File "C:\Users\patty\Documents\renpy-8.3.7-sdk\renpy\main.py", line 652, in main
    run(restart)
  File "C:\Users\patty\Documents\renpy-8.3.7-sdk\renpy\main.py", line 148, in run
    renpy.execution.run_context(True)
  File "C:\Users\patty\Documents\renpy-8.3.7-sdk\renpy\execution.py", line 958, in run_context
    context.run()
  File "game/script.rpy", line 383, in script
    call screen buttons()
  File "C:\Users\patty\Documents\renpy-8.3.7-sdk\renpy\script.py", line 1103, in lookup
    raise ScriptError("could not find label '%s'." % str(original))
ScriptError: could not find label 'candy_route'.

Windows-10-10.0.19045 AMD64
Ren'Py 8.3.7.25031702
Contamination Protocol 0.2
Sun Jul  6 17:44:21 2025
